version: '3.8'

services:
  # --- Serviço do Backend (API de Análise) ---
  backend:
    # Constrói a imagem a partir do Dockerfile no diretório atual
    build: .
    # Define um nome para a imagem construída, para referência futura
    image: orickjogando/copiloto-sdr-backend:latest
    container_name: copiloto-sdr-backend
    
    # --- CORREÇÃO DEFINITIVA ---
    # Usa o arquivo .env para carregar as variáveis de ambiente.
    env_file:
      - .env

    networks:
      - network
    restart: always
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.copiloto-backend-router.rule=Host(`backend.calculei.online`)"
        - "traefik.http.routers.copiloto-backend-router.entrypoints=websecure"
        - "traefik.http.routers.copiloto-backend-router.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.copiloto-backend-service.loadbalancer.server.port=3000"

  # --- Serviço do Frontend (React App) ---
  frontend:
    image: orickjogando/copiloto-sdr-frontend:1.0.0
    container_name: copiloto-sdr-frontend
    networks:
      - network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network"
        - "traefik.http.routers.copiloto-frontend-router.rule=Host(`copiloto.calculei.online`)"
        - "traefik.http.routers.copiloto-frontend-router.entrypoints=websecure"
        - "traefik.http.routers.copiloto-frontend-router.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.copiloto-frontend-service.loadbalancer.server.port=80"
      
networks:
  network:
    external: true