version: '3.8'

services:
  # --- Serviço do Backend (API) ---
  backend:
    # A sua imagem de backend existente
    image: orickjogando/copiloto-sdr-backend:1.0.0
    container_name: copiloto-sdr-backend
    environment:
      # Variáveis de ambiente para a API em produção
      - BASEROW_API_TOKEN=seu_token_aqui_para_producao
      - OPENAI_API_KEY=sua_chave_openai_aqui
    networks:
      - network
    deploy:
      labels:
        # Habilita o Traefik para este serviço
        - "traefik.enable=true"
        # Roteia o tráfego para o host "backend.calculei.online" para este contêiner
        - "traefik.http.routers.copiloto-backend-router.rule=Host(`backend.calculei.online`)"
        # Define os pontos de entrada para HTTPS
        - "traefik.http.routers.copiloto-backend-router.entrypoints=websecure"
        # Usa o resolvedor de certificados TLS
        - "traefik.http.routers.copiloto-backend-router.tls.certresolver=letsencryptresolver"
        # Direciona o tráfego para a porta 3000 do contêiner
        - "traefik.http.services.copiloto-backend-service.loadbalancer.server.port=3000"

  # --- Serviço do Frontend (React App) ---
  frontend:
    image: orickjogando/copiloto-sdr-frontend:1.0.0
    container_name: copiloto-sdr-frontend
    networks:
      - network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network"
        - "traefik.http.routers.copiloto-frontend-router.rule=Host(`copiloto.calculei.online`)"
        - "traefik.http.routers.copiloto-frontend-router.entrypoints=websecure"
        - "traefik.http.routers.copiloto-frontend-router.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.copiloto-frontend-service.loadbalancer.server.port=80"
      
networks:
  network:
    external: true